### ISSUE TITLE
Enable push notifications for PWA

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-app#481]
**Describe the bug**
0.27 version add the possibility to install the platform as a PWA. 
We are missing some configuration

**Fixing advice**
1. Add 2 environment variables : 
- `VAPID_PUBLIC_KEY `
- `VAPID_PRIVATE_KEY `
(use `bin/rails decidim:pwa:generate_vapid_keys` to generate the values)

2. Add these variables to the `secrets.yml`
```yaml
  vapid:
    enabled: <%%= Decidim::Env.new("VAPID_PUBLIC_KEY").to_boolean_string %>
    public_key: <%%= ENV["VAPID_PUBLIC_KEY"] %>
    private_key: <%%= ENV["VAPID_PRIVATE_KEY"] %>
```
see : https://github.com/decidim/decidim/blob/release/0.27-stable/decidim-generators/lib/decidim/generators/app_templates/secrets.yml.erb#L154C1-L157C50

**Expected behavior**
If all is well configure we should see a setting for Push notifications in the notifications settings page

**Screenshots**
![image](https://github.com/OpenSourcePolitics/decidim-app/assets/464350/40eb1267-9f20-472e-9b0b-cfbb400334d1)

**Additional context**
See discussions : 
- https://github.com/decidim/decidim/blob/release/0.27-stable/CHANGELOG.md#331-generate-the-vapid-keys-by-running-the-command
- https://github.com/decidim/decidim/pull/8774
